language: android
jdk: oraclejdk11

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.3
    - android-31
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
  - yes | sdkmanager "platforms;android-31"
  - chmod +x gradlew

script:
  - ./gradlew build
  - ./gradlew test
  - ./gradlew connectedAndroidTest

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email: false
